/**
 * SQLite SQL 生成器
 *
 * SQLite 的特殊之处：
 * 1. 使用双引号引用标识符
 * 2. INTEGER PRIMARY KEY 自动成为 ROWID 别名（自增）
 * 3. 外键需要 PRAGMA foreign_keys = ON 才能生效
 * 4. 不支持表/列注释
 * 5. ALTER TABLE 功能有限（不能删除列、改列类型等）
 */

import { DiagramData, TableNode, TableField } from '@/components/database/designer/types'
import { getDataType } from '@/config/datatypes'
import type { DatabaseType } from '@/config/datatypes/types'
import {
  escapeQuotes,
  parseTypeSize,
  getPrimaryKeyFields,
} from './shared'

/**
 * 生成 SQLite DDL
 */
export function toSQLite(diagram: DiagramData): string {
  const statements: string[] = []

  // 头部注释
  statements.push('-- SQLite DDL')
  statements.push('-- Generated by ZWD-OpsBot')
  statements.push('')

  // 启用外键支持（SQLite 默认禁用）
  statements.push('PRAGMA foreign_keys = ON;')
  statements.push('')

  // 生成表定义（包含内联外键）
  diagram.tables.forEach((table) => {
    statements.push(generateTableSQL(table, diagram))
  })

  // 生成独立索引
  const indexStatements = generateIndexes(diagram)
  if (indexStatements) {
    statements.push('')
    statements.push('-- Indexes')
    statements.push(indexStatements)
  }

  return statements.join('\n')
}

/**
 * 生成单个表的 CREATE TABLE 语句
 */
function generateTableSQL(table: TableNode, diagram: DiagramData): string {
  const lines: string[] = []

  // 字段定义
  table.fields.forEach((field) => {
    lines.push(generateFieldSQL(field, table))
  })

  // 复合主键约束（多个字段作为主键）
  const primaryKeys = getPrimaryKeyFields(table)
  if (primaryKeys.length > 1) {
    const pkFields = primaryKeys.map((f) => `"${f.name}"`).join(', ')
    lines.push(`\tPRIMARY KEY (${pkFields})`)
  }

  // 唯一约束（非主键字段）
  const uniqueFields = table.fields.filter((f) => f.unique && !f.primary)
  uniqueFields.forEach((field) => {
    lines.push(`\tUNIQUE ("${field.name}")`)
  })

  // 内联外键约束（SQLite 外键必须在 CREATE TABLE 中定义）
  const fkConstraints = generateInlineForeignKeys(table, diagram)
  fkConstraints.forEach((fk) => {
    lines.push(fk)
  })

  // 组装 CREATE TABLE
  let sql = `CREATE TABLE IF NOT EXISTS "${table.name}" (\n`
  sql += lines.join(',\n')
  sql += '\n);'

  // SQLite 不支持表注释，添加为 SQL 注释
  if (table.comment) {
    sql = `-- ${table.comment}\n` + sql
  }

  return sql
}

/**
 * 生成单个字段定义
 */
function generateFieldSQL(field: TableField, table: TableNode): string {
  const typeDef = getDataType('sqlite' as DatabaseType, field.type)
  const primaryKeys = getPrimaryKeyFields(table)
  const isOnlyPK = field.primary && primaryKeys.length === 1

  let def = `\t"${field.name}" ${parseTypeSize(field, 'sqlite')}`

  // INTEGER PRIMARY KEY 自动成为 ROWID（自增）
  // 注意：只有单一主键时才内联 PRIMARY KEY
  if (isOnlyPK) {
    def += ' PRIMARY KEY'

    // AUTOINCREMENT 关键字（可选，严格递增）
    if (field.increment && field.type.toUpperCase() === 'INTEGER') {
      def += ' AUTOINCREMENT'
    }
  }

  // NOT NULL（主键隐式 NOT NULL）
  if (field.notNull && !isOnlyPK) {
    def += ' NOT NULL'
  }

  // DEFAULT
  if (field.default !== '' && !field.increment) {
    def += ` DEFAULT ${parseSQLiteDefault(field)}`
  }

  // CHECK
  if (field.check !== '' && typeDef?.hasCheck) {
    def += ` CHECK(${field.check})`
  }

  // SQLite 不支持列注释，但可以添加行尾注释
  // 注意：这样会影响 SQL 的格式，暂不添加

  return def
}

/**
 * SQLite 默认值解析
 */
function parseSQLiteDefault(field: TableField): string {
  if (!field.default || field.default === '') return ''

  const upper = field.default.toUpperCase().trim()

  // SQLite 特有的日期时间函数
  const sqliteFunctions = [
    'CURRENT_TIMESTAMP',
    'CURRENT_DATE',
    'CURRENT_TIME',
    'DATETIME(',
    'DATE(',
    'TIME(',
    'STRFTIME(',
  ]
  if (sqliteFunctions.some((fn) => upper.startsWith(fn))) {
    return field.default
  }

  // NULL
  if (upper === 'NULL') {
    return 'NULL'
  }

  // 布尔值转换
  if (upper === 'TRUE') return '1'
  if (upper === 'FALSE') return '0'

  // 数值类型不需要引号
  const typeDef = getDataType('sqlite' as DatabaseType, field.type)
  if (typeDef && !typeDef.hasQuotes) {
    return field.default
  }

  // 文本类型需要引号
  return `'${escapeQuotes(field.default)}'`
}

/**
 * 生成内联外键约束
 */
function generateInlineForeignKeys(
  table: TableNode,
  diagram: DiagramData
): string[] {
  const constraints: string[] = []

  const relationships = diagram.relationships.filter(
    (r) => r.startTableId === table.id
  )

  relationships.forEach((rel) => {
    const endTable = diagram.tables.find((t) => t.id === rel.endTableId)
    if (!endTable) return

    const startField = table.fields.find((f) => f.id === rel.startFieldId)
    const endField = endTable.fields.find((f) => f.id === rel.endFieldId)
    if (!startField || !endField) return

    let fk = `\tFOREIGN KEY ("${startField.name}") REFERENCES "${endTable.name}" ("${endField.name}")`

    // ON DELETE
    if (rel.deleteConstraint && rel.deleteConstraint !== 'NO ACTION') {
      fk += ` ON DELETE ${rel.deleteConstraint}`
    }

    // ON UPDATE
    if (rel.updateConstraint && rel.updateConstraint !== 'NO ACTION') {
      fk += ` ON UPDATE ${rel.updateConstraint}`
    }

    constraints.push(fk)
  })

  return constraints
}

/**
 * 生成独立索引语句
 */
function generateIndexes(diagram: DiagramData): string {
  const indexStatements: string[] = []

  diagram.tables.forEach((table) => {
    table.indices.forEach((index) => {
      const indexFields = index.fields.map((f) => `"${f}"`).join(', ')
      const unique = index.unique ? 'UNIQUE ' : ''
      const indexName = index.name || `idx_${table.name}_${index.fields.join('_')}`

      indexStatements.push(
        `CREATE ${unique}INDEX IF NOT EXISTS "${indexName}" ON "${table.name}" (${indexFields});`
      )
    })
  })

  return indexStatements.join('\n')
}

export default toSQLite
